#ifndef RESTUNTS_REPLAY_VIEWER_H
#define RESTUNTS_REPLAY_VIEWER_H

#include "legacy.h"

enum REPLAY_CONTROL {
	REPLAY_CONTROL_FAST_FORWARD = 0,
	REPLAY_CONTROL_REWIND = 1,
	REPLAY_CONTROL_FAST_PLAY = 2,
	REPLAY_CONTROL_PLAY = 3,
	REPLAY_CONTROL_PAUSE = 4,
	REPLAY_CONTROL_RESTART = 5,
	REPLAY_CONTROL_MENU = 6,
	REPLAY_CONTROL_ZOOM = 7,
	REPLAY_CONTROL_PAN = 8
};

enum REPLAY_LOOP_OPERATION {
	REPLAY_LOOP_LOAD_RESOURCES = 0,
	REPLAY_LOOP_DRAW_CONTROLS = 1,
	REPLAY_LOOP_SELECT_CONTROL = 2,
	REPLAY_LOOP_HANDLE_INPUT = 3
};

#define REPLAY_LOOP_UNUSED_ARGUMENT 0

void loop_game(legacy_s16 operation, legacy_s16 recorded_frame,
	legacy_s16 current_frame);

#endif
