#ifndef RESTUNTS_TRACKDATA_LAYOUT_H
#define RESTUNTS_TRACKDATA_LAYOUT_H

#include "replay.h"

#define TRACK_GRID_SIZE 30
#define TRACK_GRID_LAST_INDEX 29
#define TRACK_TILE_POSITION_SHIFT 10U
#define TRACK_TILE_HALF_SIZE 512

#define TRACKDATA_ALLOCATION_SIZE 27635U
#define TRACKDATA_LINK_TABLE_SIZE REPLAY_TRACK_SIZE
#define TRACKDATA_AERO_TABLE_SIZE 128U
#define TRACKDATA_DIRECTION_TABLE_SIZE 96U
#define TRACKDATA_CAMERA_VECTOR_SIZE 384U
#define TRACKDATA_CHECK_VECTOR_SIZE 288U
#define TRACKDATA_HIGHSCORE_SIZE 364U
#define TRACKDATA_UNKNOWN_12_SIZE 240U
#define TRACKDATA_REPLAY_HEADER_SIZE REPLAY_GAMEINFO_SIZE
#define TRACKDATA_MAP_SIZE 901U
#define TRACKDATA_REPLAY_INPUT_BUFFER_SIZE 12000U
#define TRACKDATA_TRACK_FILE_APPEND_SIZE 1964U
#define TRACKDATA_OBJECT_INDEX_SIZE 48U
#define TRACKDATA_CHECKPOINT_DATA_SIZE 81U
#define TRACKDATA_CHECKPOINT_SECOND_OFFSET \
	(TRACKDATA_LINK_TABLE_SIZE + TRACKDATA_CHECKPOINT_DATA_SIZE)

#endif
