#ifndef RESTUNTS_TRACKDATA_LAYOUT_H
#define RESTUNTS_TRACKDATA_LAYOUT_H

#include "replay.h"

#define TRACK_GRID_SIZE 30
#define TRACK_GRID_LAST_INDEX 29
#define TRACK_TILE_POSITION_SHIFT 10U
#define TRACK_TILE_HALF_SIZE 512
#define TERRAIN_RAISED_TILE 6U
#define TERRAIN_RAISED_HEIGHT_INDEX 1U

#define TRACKDATA_ALLOCATION_SIZE 27635U
#define TRACKDATA_LINK_TABLE_SIZE REPLAY_TRACK_SIZE
#define TRACKDATA_AERO_TABLE_SIZE 128U
#define TRACKDATA_DIRECTION_TABLE_SIZE 96U
#define TRACKDATA_CAMERA_VECTOR_SIZE 384U
#define TRACKDATA_CHECK_VECTOR_SIZE 288U
#define TRACKDATA_HIGHSCORE_SIZE 364U
#define TRACKDATA_UNKNOWN_12_SIZE 240U
#define TRACKDATA_REPLAY_HEADER_SIZE REPLAY_GAMEINFO_SIZE
#define TRACKDATA_MAP_SIZE 901U
#define TRACKDATA_REPLAY_INPUT_BUFFER_SIZE 12000U
#define TRACKDATA_TRACK_FILE_APPEND_SIZE 1964U
#define TRACKDATA_OBJECT_INDEX_SIZE 48U
#define TRACKDATA_CHECKPOINT_DATA_SIZE 81U
#define TRACKDATA_CHECKPOINT_SECOND_OFFSET \
	(TRACKDATA_LINK_TABLE_SIZE + TRACKDATA_CHECKPOINT_DATA_SIZE)

enum PHYSICAL_MODEL {
	PHYSICAL_MODEL_NONE = -1,
	PHYSICAL_MODEL_START_FINISH = 0,
	PHYSICAL_MODEL_ROAD = 1,
	PHYSICAL_MODEL_SHARP_CORNER = 2,
	PHYSICAL_MODEL_LARGE_CORNER = 3,
	PHYSICAL_MODEL_CHICANE_RIGHT_LEFT = 4,
	PHYSICAL_MODEL_CHICANE_LEFT_RIGHT = 5,
	PHYSICAL_MODEL_SHARP_SPLIT_A = 6,
	PHYSICAL_MODEL_SHARP_SPLIT_B = 7,
	PHYSICAL_MODEL_LARGE_SPLIT_A = 8,
	PHYSICAL_MODEL_LARGE_SPLIT_B = 9,
	PHYSICAL_MODEL_HIGHWAY_ENTRANCE = 10,
	PHYSICAL_MODEL_HIGHWAY = 11,
	PHYSICAL_MODEL_CROSSROAD = 12,
	PHYSICAL_MODEL_RAMP = 16,
	PHYSICAL_MODEL_SOLID_RAMP = 17,
	PHYSICAL_MODEL_ELEVATED_ROAD = 18,
	PHYSICAL_MODEL_ELEVATED_SPAN = 19,
	PHYSICAL_MODEL_SOLID_ROAD = 20,
	PHYSICAL_MODEL_ELEVATED_CORNER = 21,
	PHYSICAL_MODEL_OVERPASS = 22,
	PHYSICAL_MODEL_BANKED_ENTRANCE_B = 23,
	PHYSICAL_MODEL_BANKED_ENTRANCE_A = 24,
	PHYSICAL_MODEL_BANKED_ROAD = 25,
	PHYSICAL_MODEL_BANKED_CORNER = 26,
	PHYSICAL_MODEL_LOOP = 27,
	PHYSICAL_MODEL_TUNNEL = 28,
	PHYSICAL_MODEL_PIPE_ENTRANCE = 29,
	PHYSICAL_MODEL_PIPE = 30,
	PHYSICAL_MODEL_HALF_PIPE = 31,
	PHYSICAL_MODEL_CORKSCREW_UP_DOWN_A = 32,
	PHYSICAL_MODEL_CORKSCREW_UP_DOWN_B = 33,
	PHYSICAL_MODEL_SLALOM = 34,
	PHYSICAL_MODEL_CORKSCREW_LEFT_RIGHT = 35,
	PHYSICAL_MODEL_BARN = 65,
	PHYSICAL_MODEL_GAS_STATION = 66,
	PHYSICAL_MODEL_JOES = 67,
	PHYSICAL_MODEL_OFFICE = 68,
	PHYSICAL_MODEL_WINDMILL = 69,
	PHYSICAL_MODEL_SHIP = 70
};

#endif
