seg003 segment byte public 'STUNTSC' use16
    extrn ported_sub_19F14_:proc
    extrn ported_init_rect_arrays_:proc
    extrn ported_update_frame_:proc
    extrn ported_skybox_op_helper2_:proc
    extrn skybox_op:proc
    extrn ported_transformed_shape_add_for_sort_:proc
    extrn draw_track_preview:proc
    extrn ported_draw_ingame_text_:proc
    extrn ported_do_sinking_:proc
    extrn ported_init_crak_:proc
    extrn ported_load_skybox_:proc
    extrn ported_unload_skybox_:proc
    extrn ported_load_sdgame2_shapes_:proc
    extrn ported_free_sdgame2_:proc
    extrn setup_intro:proc
    extrn ported_intro_op_:proc
seg003 ends
