seg003 segment byte public 'STUNTSC' use16
    extrn sub_19F14:proc
    extrn init_rect_arrays:proc
    extrn ported_update_frame_:proc
    extrn skybox_op_helper2:proc
    extrn skybox_op:proc
    extrn transformed_shape_add_for_sort:proc
    extrn draw_track_preview:proc
    extrn draw_ingame_text:proc
    extrn do_sinking:proc
    extrn init_crak:proc
    extrn load_skybox:proc
    extrn ported_unload_skybox_:proc
    extrn load_sdgame2_shapes:proc
    extrn ported_free_sdgame2_:proc
    extrn setup_intro:proc
    extrn intro_op:proc
seg003 ends
